apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-ci-pipeline
  namespace: hello-dev
spec:
  params:
    - name: GIT_URL
    - name: GIT_REVISION
    - name: CONTEXT_PATH
    - name: APPLICATION
    - name: PROJECT_PREFFIX    
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: source
    - name: test
      taskRef:
        name: mvn-test
      params:
        - name: CONTEXT_PATH
          value: $(params.CONTEXT_PATH)
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - clone
    - name: build
      taskRef:
        name: s2i-quarkus
      workspaces:
        - name: source
          workspace: source
      params:
        - name: TLSVERIFY
          value: "false"
        - name: PATH_CONTEXT
          value: $(params.CONTEXT_PATH)
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(params.PROJECT_PREFFIX)-dev/hello:latest
      runAfter:
        - test
    - name: deploy-dev
      taskRef:
        name: oc-deploy
      workspaces:
        - name: source
          workspace: source
      params:
        - name: DEPLOYMENT
          value: $(params.APPLICATION)
        - name: KUSTOMIZATION
          value: $(params.CONTEXT_PATH)/k8s/overlays/dev
        - name: PROJECT
          value: $(params.PROJECT_PREFFIX)-dev
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(params.PROJECT_PREFFIX)-dev/hello:latest
      runAfter:
        - build
